name: CI/CD_Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Clear npm cache
      run: npm cache clean --force
        
    - name: Update packages
      run: |
        npm install uuid@latest
        npm install debug@latest
        
    - name: Build backend
      run: |
        cd backend
        npm ci
        npm run build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Change Directory to backend
        run: cd backend
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN_BACKEND }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN_BACKEND }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_BACKEND }}
